# Application
spring.application.name=FinalProject

# MySQL config
spring.datasource.url=jdbc:mysql://localhost:3306/fileapp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=mysupersecuresecretkeymysupersecuresecretkey
jwt.access.expiration=900000
# 15 minutes in ms
jwt.refresh.expiration=86400000
# 24 hours in ms

# File storage
file.storage.location=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2MB

# Mail (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testnameqwertyuiop@gmail.com
spring.mail.password=vcczuqujowykynst
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Turn off Spring Security auth success/warn logs
logging.level.org.springframework.security=ERROR

logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.nc.FinalProject=DEBUG